kind: Service
apiVersion: v1
metadata:
  name: seed
spec:
  type: NodePort
  selector:
    app: seed
  ports:
    - name: admin
      protocol: TCP
      port: 7878
      targetPort: 7878
    - name: management
      protocol: TCP
      port: 7879
      targetPort: 7879
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: seed
  name: seed
spec:
  replicas: 1
  selector:
    matchLabels:
      run: seed
  template:
    metadata:
      labels:
        run: seed
    spec:
      containers:
      - image: phkadam2008/csw-cluster-seed
        name: seed
        imagePullPolicy: IfNotPresent
        env:
          - name: CLUSTER_PORT
            value: "3552"
          - name: CLUSTER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        command: ["bin/csw-cluster-seed"]
        args:
          - "-DclusterSeeds=$(CLUSTER_IP):$(CLUSTER_PORT)"
          - "--clusterPort=$(CLUSTER_PORT)"
          - "-DmanagementPort=7879"
        livenessProbe:
          httpGet:
            path: /members
            port: 7879
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
          - containerPort: 7878
          - containerPort: 7879
          - containerPort: 3552