kind: Service
apiVersion: v1
metadata:
  name: config
spec:
  type: NodePort
  selector:
    app: config
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: config
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - image: phkadam2008/csw-config-server
        name: config
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "bin/csw-config-server -DclusterSeeds=$(getent hosts seed-0.seed | awk '{ print $1 }'):3552 --initRepo --port=4000"]
        # command: ["bin/csw-config-server"]
        # args:
        #   - "-DclusterSeeds=$(getent hosts seed-0.seed | awk '{ print $1 }'):3552"
        #   - "-DclusterPort=$(CLUSTER_PORT)"
        #   - "--initRepo"
        #   - "--port=$(CONFIG_PORT)"
        ports:
          - containerPort: 4000
            hostPort: 4000