kind: Service
apiVersion: v1
metadata:
  name: config
spec:
  type: NodePort
  selector:
    app: config
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: config
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      initContainers:
      - name: mount-repo
        image: phkadam2008/csw-config-server
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "chown -R daemon:daemon ."]
        volumeMounts:
          - name: svn
            mountPath: "/tmp/csw-config-svn"
      containers:
      - name: config
        image: phkadam2008/csw-config-server
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "bin/csw-config-server -DclusterSeeds=$(getent hosts seed-0.seed | awk '{ print $1 }'):3552 --initRepo --port=4000"]
        ports:
          - containerPort: 4000
      volumes:
        - name: svn
          hostPath:
            path: /tmp/csw-config-svn